base_url: "https://indodax.com"

api:
  base_url: "https://indodax.com/api"
  timeout: 30

browser:
  type: chromium
  headless: true
  url: "https://indodax.com/market/USDTIDR"
  timeout: 30

mobile:
  platform: android
  android:
    platformName: Android
    automationName: UiAutomator2
    app: ${APP_APK_PATH}
    appPackage: id.co.bitcoin
    appActivity: id.co.bitcoin.ui.main.SplashScreenActivity
    deviceName: Pixel-7
    noReset: true
    newCommandTimeout: 300
